testing

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,7 @@
-#!/usr/bin/env sh
+#!/bin/bash
+
+# Exit immediately if a command exits with a non-zero status.
+set -e  
 
 # format everything
 pnpx nx format
